apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: golang-17424 
  janus-idp.io/tekton: golang-17424
  backstage.io/kubernetes-id: golang-17424
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: golang-17424
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  